name: Practicas

on:
  push:

jobs:
  verificar-compilacion:
    runs-on: ubuntu-22.04
    env:
      PRACTICAS_DIR: "practica-0,practica-1,practica-2,practica-3,practica-4,practica-5,practica-6,practica-7,practica-8,practica-9,proyecto-final"
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Gradle dependencies
        id: gradle-cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Verificar Compilacion de Directorios
        shell: bash
        run: |
          IFS=',' read -ra PRACTICAS_ARRAY <<< "$PRACTICAS_DIR"
          for directory in "${PRACTICAS_ARRAY[@]}"; do
            if [[ -d "$directory" && -f "$directory/build.gradle" ]]; then
              gradle -p $directory clean build
            else
              echo "$directory is not a gradle project."
            fi
          done
